### ISSUE TITLE
Communications are not secure

### ISSUE THREAD

**Issue by Faeriol** [Faeriol/nightwatch#1]
Lets use SSH shall we?
https://medium.com/@shazow/ssh-how-does-it-even-9e43586e4ffc
https://godoc.org/golang.org/x/crypto/ssh

**Comment by NuclearBanane** [comment]
I assume you can connect to Night Watch remotely, where do you have that portion ATM? (Since you know this, I'll find out when I get time to sit down and truly read through it).

Just trying to discuss it before attacking the problem.

**Comment by Faeriol** [comment]
Only blasts packets right now, so clients contact server

On 20 February 2015 at 14:51, Rodger <notifications@github.com> wrote:

> I assume you can connect to Night Watch remotely, where do you have that
> portion ATM? (Since you know this, I'll find out when I get time to sit
> down and truly read through it).
>
> Just trying to discuss it before attacking the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Faeriol/nightwatch/issues/1#issuecomment-75307270>.
>



-- 
Maxime Paradis
*Membre du conseil | Member of council*
Club de science informatique | Computer Science Club
Université d'Ottawa | University of Ottawa
Maxime.Paradis@uocsclub.ca
