### ISSUE TITLE
Messages for system stats

### ISSUE THREAD

**Issue by Faeriol** [Faeriol/nightwatch#2]
System stats like CPU loads and ram usage

**Comment by NuclearBanane** [comment]
Any specific system modules/tools you'd suggest? 
I'll comment here letting you know what I find. (Sometime next week)

**Comment by Faeriol** [comment]
Taking care of that one for sure

Will use gosigar probably

On 20 February 2015 at 14:49, Rodger <notifications@github.com> wrote:

> Any specific system modules/tools you'd suggest?
> I'll comment here letting you know what I find. (Sometime next week)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Faeriol/nightwatch/issues/2#issuecomment-75306999>.
>



-- 
Maxime Paradis
*Membre du conseil | Member of council*
Club de science informatique | Computer Science Club
Université d'Ottawa | University of Ottawa
Maxime.Paradis@uocsclub.ca

**Comment by Faeriol** [comment]
Commit 946a17729e60874d6627fc45f58590aaf00ba27c is a start, only we got the CPU stuff

**Comment by Faeriol** [comment]
Commit ee37988cf7e4c0392cada32c50b11a1176e2fca1
Adds mem stats

@NuclearBanane What do you think of this stuff?? It's pretty simple AND here RIGHT NOW, so if you agree Im gonna merge and we can move to secure coms, then once we have that we can discuss the next few steps

**Comment by NuclearBanane** [comment]
I reviewed the commit ee37988 and everything is good. 
:+1:  to moving on to secure communications. 

I think this issue is good to be closed. 
We can make a future issues referencing this and mark it an improvement.

**Comment by Faeriol** [comment]
Fair enough, thanks for feedback, I'll see if I have time

On 27 February 2015 at 11:15, Rodger <notifications@github.com> wrote:

> I reviewed the commit ee37988
> <https://github.com/Faeriol/nightwatch/commit/ee37988cf7e4c0392cada32c50b11a1176e2fca1>
> and everything is good.
> [image: :+1:] to moving on to secure communications.
>
> I think this issue is good to be closed.
> We can make a future issues referencing this and mark it an improvement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Faeriol/nightwatch/issues/2#issuecomment-76420626>.
>



-- 
Maxime Paradis
*Membre du conseil | Member of council*
Club de science informatique | Computer Science Club
Université d'Ottawa | University of Ottawa
Maxime.Paradis@uocsclub.ca
